




[build]
  publish = "public"
  command = ""

[[plugins]]
  package = "@netlify/plugin-prerender-spa"
  [plugins.inputs]
    crawl = ["/", "/about", "/contact", "/blog"]
    renderer = "chrome"
    staticDir = "public"